In [91]:
import numpy as np
d1=[]
A=np.random.randint(0,10,(1,10)) #I chose the numbers of arrays to be 10 
print(A)
for i in range(10):
    d1.insert(i,A[0,i])
    
print(d1)

[[7 7 0 6 8 3 7 9 9 4]]
[7, 7, 0, 6, 8, 3, 7, 9, 9, 4]


In [50]:
import numpy as np
A=np.random.randint(0,10,(3,3))
print(A)

x=A[0,0]+ A[1,1] +A[2,2]
print(x)



[[9 4 6]
 [0 5 1]
 [7 9 7]]
21


In [66]:
import numpy as np
x=3
A=np.random.randint(0,10,(1,10)) #I chose the numbers of arrays to be 10 
print(A)
for i in range (10):
    if A[0,i]>x:
        print(A[0,i])

[[0 3 9 3 9 9 0 5 6 5]]
9
9
9
5
6
5


In [85]:
import numpy as np
A=np.random.randint(0,10,(1,10))
B=np.random.randint(0,10,(1,10))
C=np.zeros(10)
print(A)
print(B)

for i in range (10):
    C=A+B
    
print(C)    

[[4 5 0 6 3 2 4 7 2 8]]
[[8 3 2 9 3 1 7 3 9 1]]
[[12  8  2 15  6  3 11 10 11  9]]


In [95]:
import numpy as np
A=np.random.randint(0,10,(1,10))
B=np.zeros(10)
print(A)
for i in range (10):
    mean=A[0,i]/10
print(mean)    
for i in range (10):
    B=A-mean
print(B)

[[9 7 1 1 5 6 6 6 4 6]]
0.6
[[8.4 6.4 0.4 0.4 4.4 5.4 5.4 5.4 3.4 5.4]]
